### ISSUE TITLE
correction in READ.ME

### ISSUE THREAD

**Issue by Jesusbill** [BIM-Tools/IFC2JSON_python#2]
This issue refers to the IFCJSON-Team forked repo where issues cannot be used, however.

In the README file, the command line for using the converter misses the python file `ifc2json.py`.
It should be like this, right?
```
python ifc2json.py -i model.ifc -o model_-_ifcjson4.json -v 4
```

**Comment by janbrouwer** [comment]
Thanks, you are right! Fixed it!
Also enabled issues on the fork.
